### ISSUE TITLE
Package in conda-forge

### ISSUE THREAD

**Issue by traversaro** [ami-iit/ADAM#26]
For packaging in projects that install all their deps via conda-forge without resorting to PyPI, I would like to package this via conda-forge . This should be trivial to do, generating the recipe via grayskull ( https://github.com/conda-incubator/grayskull ). Unfortunatly the tricky aspect is that there is no [urdf-parser-py](https://github.com/ros/urdf_parser_py) package on conda-forge, so we should first package that dep in conda-forge.

**Comment by Giulero** [comment]
Hi @traversaro! I missed this, sorry! Indeed it would be nice to ship the library via conda-forge :)
I could start packaging `urdf-parser-py` (maybe I'll need some advice from you :D).

**Comment by traversaro** [comment]
We hitted this with @DanielePucci today, even if the work around of just using pip to install inside the conda environment worked fine.

**Comment by traversaro** [comment]
I proposed the recipe in conda-forge in https://github.com/conda-forge/staged-recipes/pull/21894 .

**Comment by traversaro** [comment]
This was fixed:
* https://github.com/conda-forge/staged-recipes/pull/21894
* https://github.com/ami-iit/ADAM/pull/43

> We hitted this with @DanielePucci today, even if the work around of just using pip to install inside the conda environment worked fine.

I do not remember anything related to this, but basically now you can install it in an existing environment:
~~~
mamba install -c conda-forge adam-robotics
~~~
or create a new environment with:
~~~
mamba create -n adamenv -c conda-forge adam-robotics
~~~
