### ISSUE TITLE
Required python version

### ISSUE THREAD

**Issue by jake-levy** [ami-iit/ADAM#46]
Hello - 

Here, you are requiring Python 3.8 or later.
https://github.com/ami-iit/ADAM/blob/bffcc3cf1af34a0d28238da9105044f40124d44d/setup.cfg#L28

I was wondering if you would consider changing to `>=3.7` instead. I want to use your package with [NVIDIA Isaac Sim](https://developer.nvidia.com/isaac-sim), which uses Python 3.7.13.

**Comment by DanielePucci** [comment]
CC @Giulero

**Comment by jake-levy** [comment]
Ah ok; thanks!

**Comment by Giulero** [comment]
@jake-levy python version changed! https://github.com/ami-iit/ADAM/pull/47

**Comment by jake-levy** [comment]
Thank you!!
