### ISSUE TITLE
Jax installation for GPU

### ISSUE THREAD

**Issue by stergiosba** [ami-iit/adam#50]
The Jax pip installation only comes with the CPU version of Jax. Is this intended?
```pip install adam-robotics[jax]```

**Comment by traversaro** [comment]
fyi @Giulero @flferretti

**Comment by flferretti** [comment]
By default, the installation of JAX comes with the CPU version of `jaxlib`. If you're interested in the GPU version, I'd suggest to install it as per the [JAX documentation](https://jax.readthedocs.io/en/latest/installation.html#pip-installation-gpu-cuda-installed-via-pip-easier):

```python
pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html ```

**Comment by stergiosba** [comment]
Personally I am aware of the installation process for using the GPU with Jax. I just wanted to point this out so that others are not confused when their code is not as fast as they hoped.

**Comment by traversaro** [comment]
> Personally I am aware of the installation process for using the GPU with Jax. I just wanted to point this out so that others are not confused when their code is not as fast as they hoped.

Good point, would you be interested (if it is ok for the mantainer @Giulero) to add a sentence in the readme warning about this and perhaps linking to https://github.com/google/jax#instructions ?

**Comment by Giulero** [comment]
Thanks @stergiosba for opening the issue! @flferretti is right.
Yes @traversaro, I agree!

**Comment by Giulero** [comment]
I guess this is solved. Closing!

**Comment by traversaro** [comment]
As an additional info for anyone finding this via Google, since ~May 2025 the `jax` package on conda-forge on Linux amd64 by default installs a working GPU-enabled jax, i.e.:

~~~
conda create -n adamjax -c conda-forge adam-robotics jax
~~~

on a `linux-64` system with a working NVIDIA driver installation install a GPU-power jax out of the box.
