### ISSUE TITLE
Fix failing Conda github actions

### ISSUE THREAD

**Issue by Giulero** [ami-iit/ADAM#52]
The github conda actions are failing. It seems related to some sort of incompatibility between the new python default version installed in conda (the `3.12`) and jax/pytorch.  See for example https://github.com/ami-iit/ADAM/actions/runs/7081140778

I did a test, check here https://github.com/ami-iit/ADAM/actions/runs/6903254530. 
We might fix the python version, even though I'm not sure it's the best solution/

**Comment by traversaro** [comment]
> I did a test, check here https://github.com/ami-iit/ADAM/actions/runs/6903254530.\nWe might fix the python version, even though I'm not sure it's the best solution/

Either we fix the python version, or we install jax pytorch and python in one shot, so that the solver decides on an appropriate python version.
