### ISSUE TITLE
Rename this repo to adam-robotics?

### ISSUE THREAD

**Issue by traversaro** [ami-iit/adam#54]
As the package is installed as `adam-robotics` in PyPI and conda-forge, perhaps for discoverability and clarity it is better to rename this repo to `adam-robotics` as well?

@Giulero

**Comment by traversaro** [comment]
Any opinion on this @Giulero ?

**Comment by Giulero** [comment]
Hi @traversaro! Sorry for the late reply. You're right! However, honestly, I do not like the name `adam-robotics` a lot, but this is only a personal preference!  
I was forced to use this name in PyPI since obviously the name `adam` was already taken :smile: 
I can start to add a tag but if there is a general consensus we can also change the name!

**Comment by traversaro** [comment]
Ok, as you prefer, for discoverability it is easier to use the same name, but if you do not like it no problem, it was only a suggestion. What do you mean with "I can start to add a tag"?

**Comment by Giulero** [comment]
> What do you mean with "I can start to add a tag"?

Wrong naming! I mean `topic`, the tags we add in the repo description.

**Comment by traversaro** [comment]
Ahh, I do not think it help a lot, but for sure better then anything. I think we can close this issue then.

**Comment by Giulero** [comment]
> Ahh, I do not think it help a lot

Me neither, honestly :smiling_face_with_tear:

**Comment by traversaro** [comment]
Another suggestion: can we at least rename it `adam` instead of `ADAM` ? At least we are consistent between `import adam` and the name of the repo.

**Comment by Giulero** [comment]
Yeah, it's a nice idea! I also have to change some instances in the readme.

**Comment by traversaro** [comment]
> Yeah, it's a nice idea! I also have to change some instances in the readme.

Ok, can I proceed with the rename ADAM/adam?

**Comment by traversaro** [comment]
Ok,  I see th repo was renamed, great.
