### ISSUE TITLE
NAN value

### ISSUE THREAD

**Issue by 21spike21** [ami-iit/adam#78]
Hi , 
I'm using your library but I don't understand why I got only a Nan value in the Mass matrix and the bias
https://github.com/21spike21/Casadi

**Comment by traversaro** [comment]
Hi @21spike21, are you related to @tommasoandina1? The code you linked has been committed by @tommasoandina1 . In any case, please reply to the questions in https://github.com/ami-iit/adam/issues/77#issuecomment-2100401915, and check also the advice there.

fyi @Giulero

**Comment by 21spike21** [comment]
Yep, we work together

**Comment by Giulero** [comment]
I guess this is addressed in #77. Closing
