### ISSUE TITLE
Test ADAM with conda-forge dependencies failing on macos-latest

### ISSUE THREAD

**Issue by Giulero** [ami-iit/adam#79]
The action running the conda-forge dependency test is failing when testing macos-lates: 
https://github.com/ami-iit/adam/actions/runs/9026258191/job/24803267789

**Comment by traversaro** [comment]
The problem is probably that `macos-latest` now points to `macos-14`, that is `osx-arm64` (i.e. arm processors) instead of `osx-64` (intel processors). And apparently we do not have `urdfdom-py` on `osx-arm64` ?

**Comment by traversaro** [comment]
This will be fixed by https://github.com/conda-forge/urdfdom-py-feedstock/pull/6 .

**Comment by Giulero** [comment]
Thanks @traversaro !

**Comment by traversaro** [comment]
> This will be fixed by [conda-forge/urdfdom-py-feedstock#6](https://github.com/conda-forge/urdfdom-py-feedstock/pull/6) .

This was merged, so the job should be green again the next time it runs.

**Comment by Giulero** [comment]
Thanks a lot @traversaro for solving this ! :)

**Comment by traversaro** [comment]
Green: https://github.com/ami-iit/adam/actions/runs/9248193736 .
